name: 'Build and test action'
description: 'Build and test something'
inputs:
  bt-param:  # id of input
    description: 'Build and test params'
    required: true
  artifact-name:  # id of input
    description: 'Artifact name'
    required: true
runs:
  using: "composite"
  steps:
    - run: |
        # Handle params first
        $bt = "${{ inputs.bt-param }}"
        $name = "${{ inputs.artifact-name }}"
        $outPath = "${{ github.workspace }}/artifactTests/$name"
        
        dotnet test $bt -o $outPath
      shell: pwsh