name: 'Build and test action'
description: 'Build and test something'
inputs:
  bt-param:  # id of input
    description: 'Build and test params'
    required: true
  artifact-name:  # id of input
    description: 'Artifact name'
    required: true
runs:
  using: "composite"
  steps:
    - run: dotnet test $env:BT_PARAM -o "${{github.workspace}}/artifactTests/$env:ARTIFACT_NAME"
      env:
          BT_PARAM: ${{ inputs.bt-param }}
          ARTIFACT_NAME: ${{ inputs.artifact-name}}
      shell: pwsh