name: 'Setup Windows browser action'
description: 'Make sure latest browser version is installed'
runs:
  using: "composite"
  steps:
    - run: choco upgrade googlechrome --ignore-checksums
      shell: pwsh 
    - run: choco upgrade firefox --ignore-checksums
      shell: pwsh
